name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      # Instalar dependencias de Node.js
      - name: Install dependencies
        run: npm install

      # Ejecutar pruebas con Jest
      - name: Run tests
        run: npx jest

      # Desplegar a Heroku solo si las pruebas pasan
      - name: Deploy to Heroku
        if: success() # Solo si las pruebas pasan
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: "HRKU-e9727b0e-2552-40c3-8a79-b5030f36101a"
          heroku_app_name: "api-seguridad"
          heroku_email: "dportillop1@miumg.edu.gt"
          branch: "main"
